name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove old 3D Contribution Graph
        run: |
          [ -d "profile-3d-contrib" ] && rm -rf profile-3d-contrib
        continue-on-error: true

      - name: Generate GitHub 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: beunyeong

      - name: Commit & Push
        run: |
          git config user.name "beunyeong"
          git config user.email "beunyeong.b@gmail.com"
          git pull origin main --rebase || echo "Pull failed, skipping rebase."
          
          DATE=$(date +'%Y-%m-%d')
          git add -A .
          git commit -m "Update: ${DATE} 3D 그래프 업데이트" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
