name: GitHub-Profile-3D-Contrib

on:
  schedule: # 매일 03:00 KST 실행
    - cron: "0 18 * * *" 
  workflow_dispatch: # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib 
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1 
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: beunyeong
      - name: Commit & Push 
        run: |
          git config user.name "beunyeong"
          git config user.email "beunyeong.b@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/beunyeong/beunyeong.git
          git pull origin main --rebase || echo "Pull failed, continue anyway."
          git add -A .
          git commit -m "Feat: 3D-Graph 파일 업데이트" || echo "커밋할 변경 사항이 없습니다"
          git push origin main
