name: GitHub-Profile-3D-Contrib

on:
  schedule: # 매일 03:00 KST 실행
    - cron: "0 18 * * *" 
  workflow_dispatch: # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib 
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: beunyeong/profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: beunyeong

      - name: Commit & Push 
        run: |
          git config user.name "beunyeong"
          git config user.email "beunyeong.b@gmail.com"
          git add -A .
          git commit -m "Feat: 3D-Graph 파일 업데이트" || echo "커밋할 변경 사항이 없습니다"
          git push origin main
