name: Update Blog Posts

on:
  schedule:
    - cron: '0 */12 * * *'  # 12시간마다 실행 (원하는 시간으로 변경 가능)
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  update-readme:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://beunyeong.tistory.com/rss"
